.TH "pfsabsolute" 1
.SH NAME
pfsabsolute \- Convert luminance in images to absolute measure
.SH SYNOPSIS
.B pfsabsolute
<dest Y> [<src Y>] [--verbose] [--help]
.SH DESCRIPTION
\fBpfsabsolute\fR applies all necessary operations to convert an image
from relative luminance (tag LUMINANCE is RELATIVE) or
display-dependent luma (tag LUMINANCE is DISPLAY) to absolute
luminance values. When the luminance in an image is absolute (tag
LUMINANCE set to ABSOLUTE), the Y channel represents physical
luminance in cd/m^2. Absolute luminance levels are useful for some
tone mapping algorithms and also for image or video compression.

The argument \fB<dest Y>\fR denotes the level of luminance that
relative luminance \fB<src Y>\fR should be rescaled to. The luminance
is in fact multiplied by the ratio <dst Y>/<src Y>. \fB<src Y>\fR is
normally relative luminance checked with pfsview in the spot where the
absolute luminance \fB<dest Y>\fR is measured, known or guessed. If
\fB<src Y>\fR is omitted, the value 1 is assumed, so \fB<dest Y>\fR is
just a scaling factor.

In case if display-depended luma (tag LUMINANCE is DISPLAY), the
inverse gamma correction is applied (assuming sRGB color space). In
such case \fB<dest Y>\fR is usually the maximum luminance of a display
(e.g. 80 cd/m^2).

This command always sets LUMINANCE tag to ABSOLUTE.

.SH EXAMPLES
.TP
pfsin memorial.hdr | pfsabsolute 20 0.04 | pfsview

Multiply luminance in memorial image, so that relative luminance 0.04
becomes 20 cd/m^2. Normally, the value 0.04 is check using pfsview in
the spot, where the absolute luminance (which equals in this case 20
cd/m^2) is known.

.TP
pfsin lena.png | pfsabsolute 80 | pfsview

Convert lena image from sRGB color space to absolute XYZ, assuming
maximum luminance of the monitor 80 cd/m^2.

.SH "SEE ALSO"
.BR pfsgamma (1)
.BR pfsinppm (1)
.SH BUGS
Please report bugs and comments to Rafal Mantiuk
<mantiuk@mpi-sb.mpg.de>.
