.TH "pfsflip" 1
.SH NAME
pfsflip \- Flip images horizontally and/or vertically.
.SH SYNOPSIS
.B pfsflip
[--h] [--v] [--help]
.SH DESCRIPTION
Use this command to flip images from a stream of pfs. The --h option results in
a horizontal exchange, and the --v option results in a vertical exchange. Both
options may be applied, which is equivalent to rotation of the image 180
degrees.

.SH OPTIONS
.TP
--h, -h

Flip the image horizontally.

.TP
--v, -v

Flip the image vertically.

.SH EXAMPLES
.TP
pfsin memorial.hdr | pfsflip -h -v | pfsout memorial_gc.hdr

Flip memorial image horizontally and vertically (rotate the image 180 degrees)
and save to memorial_gc.hdr.

.SH "NOTES"
Notice that either --h or --v must be specified.

.SH "SEE ALSO"
.BR pfsin(1)
.BR pfsout(1)
.BR pfsrotate(1)

.SH BUGS
Please report bugs and comments to Alexander Efremov
<aefremov@mpi-sb.mpg.de>.
