.TH "pfsoctavelum" 1
.SH NAME
pfsoctavelum \- Process luminance in pfs stream using Octave
.SH SYNOPSIS
.B pfsoctavelum <octave_program>
.SH DESCRIPTION
Use this command to execute a GNU Octave program on luminance channel of each
frame in the pfs stream. \fIoctave_program\fR must be given in
quotation marks ("") and must not produce any output (it can output to
stderr, not to stdout). Color channels are scaled proportionaly to the
luminance channel. Luminance channel is represented by matrix \fIY\fR.
.PP
Note: This command requires GNU Octave.
.SH EXAMPLES
.TP
pfsinrgbe frames_%04d.hdr | pfsoctavelum "Y = conv2( Y, gaussian( 10, 1/5 )*gaussian( 10, 1/5 )', 'same' );" | pfsview
.PP
Blur the sequence of frames with gaussian blur and show the result
with pfsview.
.SH BUGS
Please report bugs and comments to Rafal Mantiuk
<mantiuk@mpi-sb.mpg.de>.


